#!/bin/bash

# CodinGame planet is being attacked by slimy insectoid aliens.
# <---
# Hint:To protect the planet, you can implement the pseudo-code provided in the statement, below the player.


# game loop
arrayName=("nul" "nul" "nul" "nul" "nul" "nul" "nul" "nul" "nul" "nul")
arrayDist=(0 0 0 0 0 0 0 0 0 0)
arraySpeed=(0 0 0 0 0 0 0 0 0 0)

while true; do
    # enemy1: name of enemy 1
    read enemy1
    # dist1: distance to enemy 1
    read dist1
    # enemy2: name of enemy 2
    read enemy2
    # dist2: distance to enemy 2
    read dist2
    
    echo "Debug messages..." "enemy1" $enemy1 "dist1" $dist1 "enemy2" $enemy2 "dist2" $dist2 >&2
    if [[ $enemy1 == "Nobody" ]]; then
        echo $enemy2
    elif [[ $enemy2 == "Nobody" ]]; then
        echo $enemy1
    fi

    if [[ $enemy1 != "Nobody" && $enemy2 != "Nobody" ]]; then
    
        i=0
        n=10
        ind1=10
        ind2=10
        
        while [ $i -lt $n ]; do
            if [[ ${arrayName[$i]} == $enemy1 ]]; then
                arraySpeed[$i]=`expr ${arrayDist[$i]} - $dist1`
                arrayDist[$i]=$dist1
                if [[ $ind1 != 10 ]]; then
                    arrayName[$ind1]="nul"
                    arraySpeed[$ind1]=0
                    arrayDist[$ind1]=0
                fi
                ind1=$i
            fi
            if [[ ${arrayName[$i]} == "nul" && $ind1 == 10 ]]; then
                ind1=$i
                arrayName[$ind1]=$enemy1
                arraySpeed[$ind1]=0
                arrayDist[$ind1]=$dist1
            fi
            if [[ ${arrayName[$i]} == $enemy2 ]]; then
                arraySpeed[$i]=`expr ${arrayDist[$i]} - $dist2`
                arrayDist[$i]=$dist2
                if [[ $ind2 != 10 ]]; then
                    arrayName[$ind2]="nul"
                    arraySpeed[$ind2]=0
                    arrayDist[$ind2]=0
                fi
                ind2=$i
            fi
            if [[ ${arrayName[$i]} == "nul" && $ind2 == 10 ]]; then
                ind2=$i
                arrayName[$ind2]=$enemy2
                arraySpeed[$ind2]=0
                arrayDist[$ind2]=$dist2
            fi
            i=`expr $i + 1`
        done
        
        echo "Debug messages..." "ind1" $ind1 "ind2" $ind2 >&2
        echo "Debug messages..." "name1" ${arrayName[$ind1]} "name2" ${arrayName[$ind2]} >&2
        echo "Debug messages..." "speed1" ${arraySpeed[$ind1]} "speed2" ${arraySpeed[$ind2]} >&2
        echo "Debug messages..." "dist1" ${arrayDist[$ind1]} "dist2" ${arrayDist[$ind2]} >&2
    
        nextdist1=`expr ${arrayDist[$ind1]} - ${arraySpeed[$ind1]}`
        nextdist2=`expr ${arrayDist[$ind2]} - ${arraySpeed[$ind2]}`
    
        if [[ $nextdist1 -lt $nextdist2 ]]; then
            arrayName[$ind1]="nul"
            arraySpeed[$ind1]=0
            arrayDist[$ind1]=0
            echo $enemy1
        else
            echo $enemy2
            arrayName[$ind2]="nul"
            arraySpeed[$ind2]=0
            arrayDist[$ind2]=0
        fi
        echo "Debug messages..."  ${arrayName[*]} >&2
    fi
    
    # Write an action using echo
    # To debug: echo "Debug messages..." >&2

    # echo "name of the enemy" # You have to output a correct ship name to shoot ("Buzz", enemy1, enemy2, ...)
done
